name: Main workflow

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install shfmt
        run: brew install shellcheck shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .

      - name: Run shellcheck
        run: shellcheck src/*
