name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install shfmt
        run: sudo snap install shfmt

      - name: Run shfmt
        run: shfmt -d -i 2 -ci .

      - name: Run shellcheck
        run: shellcheck ./src/*
