name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    name: Lint shell scripts
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout tree
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@3cdb78d0f62ad29dd32de765782654f4eedea607 # 2026.08.31.1

      - name: Install shellcheck and shfmt
        run: brew install shellcheck shfmt

      - parallel:
          - name: Check formatting with shfmt
            run: shfmt -d -i 2 -ci .

          - name: Lint with shellcheck
            run: shellcheck src/*
